package com.evanmclean.erudite;

import com.google.common.collect.ImmutableList;

/**
 * A set of articles, plus any error messages that may have been returned by the
 * source.
 *
 * @author Evan M<sup>c</sup>Lean, <a href="http://evanmclean.com/"
 *         target="_blank">M<sup>c</sup>Lean Computer Services</a>
 */
public class Articles
{
  private final ImmutableList<? extends Article> articles;
  private final ImmutableList<String> errors;

  public Articles( final ImmutableList<? extends Article> articles )
  {
    this(articles, ImmutableList.<String> of());
  }

  public Articles( final ImmutableList<? extends Article> articles,
      final ImmutableList<String> errors )
  {
    this.articles = articles;
    this.errors = errors;
  }

  /**
   * List of articles to process.
   *
   * @return List of articles to process.
   */
  public ImmutableList<? extends Article> getArticles()
  {
    return articles;
  }

  /**
   * Any non-fatal errors generated by the source while retrieving the articles.
   *
   * @return List (usually empty) of non-fatal error messages.
   */
  public ImmutableList<String> getErrors()
  {
    return errors;
  }
}
